// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB10lEhwP6ppHDnO2lPiebkSZclrnA8VYM',
    appId: '1:844175847833:web:c5e3b0d9cb404fdc1e6308',
    messagingSenderId: '844175847833',
    projectId: 'salutepfi',
    authDomain: 'salutepfi.firebaseapp.com',
    storageBucket: 'salutepfi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTPqk4rALSIJWRscJtCJxhgBhseMlhvxY',
    appId: '1:844175847833:android:afd1ef2983eb57071e6308',
    messagingSenderId: '844175847833',
    projectId: 'salutepfi',
    storageBucket: 'salutepfi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkpvBJBaJ4vGsNF1NLg_6CEGmIpHTKXQM',
    appId: '1:844175847833:ios:befe46f8a514208a1e6308',
    messagingSenderId: '844175847833',
    projectId: 'salutepfi',
    storageBucket: 'salutepfi.appspot.com',
    iosBundleId: 'com.example.salutepfi',
  );
}
